version: '3.8'

services:
  # DynamoDB Local for development
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    environment:
      - JAVA_OPTS=-Xmx1g

  # DynamoDB Admin (Web UI)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  # Serverless Offline (for local API testing)
  serverless-api:
    build:
      context: .
      dockerfile: Dockerfile.serverless
    container_name: serverless-api
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - DYNAMODB_TABLE=kelly-user-management-dev-users
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - dynamodb-local
    volumes:
      - .:/app
      - /app/node_modules

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - serverless-api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  dynamodb_data:
