name: Deploy Serverless App

on:
  push:
    branches: [main, production]
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production

env:
  AWS_REGION: us-east-1
  SERVICE_NAME: kelly-user-management

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lambda.txt
          pip install pytest
      
      - name: Run tests
        run: |
          python -m pytest src/tests/ -v || echo "No tests found"
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    outputs:
      api-url: ${{ steps.deploy.outputs.api-url }}
      frontend-url: ${{ steps.deploy.outputs.frontend-url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Serverless Framework
        run: |
          npm install -g serverless
          npm install --save-dev serverless-python-requirements serverless-offline
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deploy serverless backend
        id: deploy
        run: |
          STAGE="${{ github.event.inputs.stage || 'dev' }}"
          
          # Deploy serverless stack
          serverless deploy --stage $STAGE --region ${{ env.AWS_REGION }}
          
          # Get API URL
          API_URL=$(serverless info --stage $STAGE --region ${{ env.AWS_REGION }} | grep "ServiceEndpoint:" | sed 's/ServiceEndpoint: //')
          echo "api-url=$API_URL" >> $GITHUB_OUTPUT
          
          # Get frontend bucket
          FRONTEND_BUCKET=$(aws cloudformation describe-stacks \
            --stack-name "${{ env.SERVICE_NAME }}-$STAGE" \
            --region ${{ env.AWS_REGION }} \
            --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' \
            --output text)
          
          # Get CloudFront URL
          CLOUDFRONT_URL=$(aws cloudformation describe-stacks \
            --stack-name "${{ env.SERVICE_NAME }}-$STAGE" \
            --region ${{ env.AWS_REGION }} \
            --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontUrl`].OutputValue' \
            --output text)
          
          echo "frontend-url=https://$CLOUDFRONT_URL" >> $GITHUB_OUTPUT
          echo "FRONTEND_BUCKET=$FRONTEND_BUCKET" >> $GITHUB_ENV
          echo "API_URL=$API_URL" >> $GITHUB_ENV
      
      - name: Deploy frontend
        run: |
          cd frontend
          
          # Install dependencies
          npm ci
          
          # Build React app
          REACT_APP_API_URL="${{ steps.deploy.outputs.api-url }}" npm run build
          
          # Upload to S3
          aws s3 sync build/ s3://${{ env.FRONTEND_BUCKET }}/ --delete
          
          # Invalidate CloudFront cache
          DISTRIBUTION_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Origins.Items[0].DomainName=='${{ env.FRONTEND_BUCKET }}.s3.amazonaws.com'].Id" \
            --output text)
          
          if [ ! -z "$DISTRIBUTION_ID" ]; then
            aws cloudfront create-invalidation \
              --distribution-id $DISTRIBUTION_ID \
              --paths "/*"
          fi

  test-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test API deployment
        run: |
          sleep 30  # Wait for deployment to propagate
          
          echo "Testing API at: ${{ needs.deploy.outputs.api-url }}"
          
          # Test health endpoint
          HEALTH_RESPONSE=$(curl -s "${{ needs.deploy.outputs.api-url }}/api/health")
          echo "Health response: $HEALTH_RESPONSE"
          
          if echo "$HEALTH_RESPONSE" | grep -q "healthy"; then
            echo "✅ API health check passed!"
          else
            echo "❌ API health check failed!"
            exit 1
          fi
          
          # Test users endpoint
          USERS_RESPONSE=$(curl -s "${{ needs.deploy.outputs.api-url }}/api/users")
          echo "Users response: $USERS_RESPONSE"
          
          if echo "$USERS_RESPONSE" | grep -q "\[\]"; then
            echo "✅ Users endpoint working!"
          else
            echo "⚠️ Users endpoint may have issues"
          fi

  notify:
    needs: [deploy, test-deployment]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify deployment status
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ] && [ "${{ needs.test-deployment.result }}" == "success" ]; then
            echo "🎉 Serverless deployment successful!"
            echo "🚀 API URL: ${{ needs.deploy.outputs.api-url }}"
            echo "🌐 Frontend URL: ${{ needs.deploy.outputs.frontend-url }}"
            echo "🔍 Health Check: ${{ needs.deploy.outputs.api-url }}/api/health"
            echo ""
            echo "📊 Architecture: AWS Lambda + API Gateway + DynamoDB + S3 + CloudFront"
          else
            echo "❌ Serverless deployment failed!"
            exit 1
          fi
